import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from "@/components/sidebar";
import TopNavbar from "@/components/topNavbar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <div className="flex">
      <aside className="w-64 h-full shadow">
        <Sidebar />
      </aside>

      <div className="bg-[#F8F7FA] w-[80%] h-full">
        <div className="px-6 relative">
          {/* Top Navbar  */}
          <TopNavbar />
          <div className="pt-4">
          {children}
          </div>
          {/* Footer */}
          {/* <Footer /> */}
        </div>
      </div>
    </div>
      </body>
    </html>
  )
}
